version: '3.8'

services:
  rag:
    build: .
    target: base
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped 