vector_store:
  persist_directory: ./data/vectorstore
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  collection_name: research_documents

rag:
  model_name: claude-3-haiku-20240307
  temperature: 0.1
  max_tokens: 1000
  system_prompt_path: ./personal_rag/retrieval/prompts/rag_system_prompt.txt
  query_prompt_path: ./personal_rag/retrieval/prompts/rag_query_prompt.txt

blog_scraper:
  timeout: 30
  user_agent: "RAG Research Bot 1.0"

document_processor:
  chunk_size: 1000
  chunk_overlap: 200